version: "3.9"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user_name"
      POSTGRES_PASSWORD: "user_password"
    volumes:
      - ./../database_helper/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"